// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using teams.Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260322215149_TeamMemberUserNavigation")]
    partial class TeamMemberUserNavigation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("teams.Entities.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("teams.Entities.Models.ProjectTeam", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("ProjectTeams");
                });

            modelBuilder.Entity("teams.Entities.Models.SyncedUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("UserId");

                    b.ToTable("SyncedUsers");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e3a5e7de-975c-4d0f-ad17-cd563e62789a"),
                            Email = "alice.parker@company.com",
                            Name = "Alice Parker"
                        },
                        new
                        {
                            UserId = new Guid("251e0a52-d589-4845-ada8-daeb08be76ea"),
                            Email = "anna.collins@company.com",
                            Name = "Anna Collins"
                        },
                        new
                        {
                            UserId = new Guid("024e414c-d9d9-477a-bcb5-c6777bc7d3f9"),
                            Email = "carol.green@company.com",
                            Name = "Carol Green"
                        },
                        new
                        {
                            UserId = new Guid("0eae7ece-6671-4f83-9caa-fc2d8eadd9ae"),
                            Email = "philip.davis@company.com",
                            Name = "Philip Davis"
                        },
                        new
                        {
                            UserId = new Guid("db21f4f6-0eb4-4905-a604-ae5ab05696a6"),
                            Email = "florence.reed@company.com",
                            Name = "Florence Reed"
                        },
                        new
                        {
                            UserId = new Guid("f1cc0ba3-1050-43f7-86bd-98d4b7f7e216"),
                            Email = "john.foster@company.com",
                            Name = "John Foster"
                        },
                        new
                        {
                            UserId = new Guid("804eef0f-2ec6-4b19-8b54-3373388f122b"),
                            Email = "mary.allen@company.com",
                            Name = "Mary Allen"
                        },
                        new
                        {
                            UserId = new Guid("faf84edb-dd0b-4de9-90f9-3671335d01c7"),
                            Email = "sandra.quinn@company.com",
                            Name = "Sandra Quinn"
                        },
                        new
                        {
                            UserId = new Guid("4b93b0ab-aed4-4eb1-a40b-900229359841"),
                            Email = "louis.newton@company.com",
                            Name = "Louis Newton"
                        },
                        new
                        {
                            UserId = new Guid("fb874eba-9c48-4340-a690-bebb2195d379"),
                            Email = "admin@admin.com",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("teams.Entities.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("teams.Entities.Models.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("teams.Entities.Models.ProjectTeam", b =>
                {
                    b.HasOne("teams.Entities.Models.Project", "Project")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("teams.Entities.Models.Team", "Team")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("teams.Entities.Models.TeamMember", b =>
                {
                    b.HasOne("teams.Entities.Models.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("teams.Entities.Models.SyncedUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("teams.Entities.Models.Project", b =>
                {
                    b.Navigation("ProjectTeams");
                });

            modelBuilder.Entity("teams.Entities.Models.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("ProjectTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
