// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("fb874eba-9c48-4340-a690-bebb2195d379"),
                            RoleId = new Guid("418b0ac3-4dba-4ccf-883e-63fdd7ac62a9")
                        },
                        new
                        {
                            UserId = new Guid("e3a5e7de-975c-4d0f-ad17-cd563e62789a"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("251e0a52-d589-4845-ada8-daeb08be76ea"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("024e414c-d9d9-477a-bcb5-c6777bc7d3f9"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("0eae7ece-6671-4f83-9caa-fc2d8eadd9ae"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("db21f4f6-0eb4-4905-a604-ae5ab05696a6"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("f1cc0ba3-1050-43f7-86bd-98d4b7f7e216"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("804eef0f-2ec6-4b19-8b54-3373388f122b"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("faf84edb-dd0b-4de9-90f9-3671335d01c7"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("4b93b0ab-aed4-4eb1-a40b-900229359841"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("backend.Entities.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("418b0ac3-4dba-4ccf-883e-63fdd7ac62a9"),
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9"),
                            Name = "Funcionario",
                            NormalizedName = "FUNCIONARIO"
                        });
                });

            modelBuilder.Entity("backend.Entities.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3a5e7de-975c-4d0f-ad17-cd563e62789a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0981140-1b7c-4f33-a556-8ce519876d66",
                            Email = "apinto@pessoal.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Ana Alexandra Valença Pinto",
                            NormalizedEmail = "APINTO@PESSOAL.PT",
                            PasswordHash = "AQAAAAIAAYagAAAAENLLmW3rVmFlf8TaNCL5neMQ2dlb4Tqdmk8wmyech/l1LR0NrhCyYPNg5GVPixZE9Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "82a360c3-37f9-42da-9dd2-e8af93b864fc",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("251e0a52-d589-4845-ada8-daeb08be76ea"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1635a002-94d3-44ef-86bb-57748d6b5654",
                            Email = "acasaco@pessoal.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Ana Cristina Leite Casaco",
                            NormalizedEmail = "ACASACO@PESSOAL.PT",
                            PasswordHash = "AQAAAAIAAYagAAAAEIDVzMG1GxuV1nz0VAKeh2s5+6SNWxHgrMQVsfltRGRgB30T5Svv8i96lxbNy6O5ew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9dce8fcf-555e-475b-a676-0336b4a2886e",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("024e414c-d9d9-477a-bcb5-c6777bc7d3f9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5701278b-d7ec-40ba-9cd6-708c44563c16",
                            Email = "cazevedo@pessoal.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Carla Alexandra Gomes Azevedo",
                            NormalizedEmail = "CAZEVEDO@PESSOAL.PT",
                            PasswordHash = "AQAAAAIAAYagAAAAEA/Jq/pyjdaYZPHHJpHbqp+i+5+OsgUefuEAQkvooVZb58I6rxZyxF8urU87vWNi3w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "75da7095-038e-4aca-970a-23122ef0e9c7",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("0eae7ece-6671-4f83-9caa-fc2d8eadd9ae"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e5607436-cab6-4d49-bf0a-2a3f595fd1f7",
                            Email = "fdias@pessoal.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Filipe Manuel Marques da Silva Dias",
                            NormalizedEmail = "FDIAS@PESSOAL.PT",
                            PasswordHash = "AQAAAAIAAYagAAAAEPndwjT6ExopmCYz9Aq9PrmtPPkq9lUQdddp76wbeRyhTVzEbGN+74hauKGZUWrVng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bf601b92-1997-477c-a5b3-8958adc58474",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("db21f4f6-0eb4-4905-a604-ae5ab05696a6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "85ce73c8-afd1-4679-bd8b-8cf37c891da0",
                            Email = "frebelo@pessoal.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Filomena Maria Cruz Rebelo",
                            NormalizedEmail = "FREBELO@PESSOAL.PT",
                            PasswordHash = "AQAAAAIAAYagAAAAEBDhOkl+BmTH6/kLA+Lwjzg9lgE3khGaNJ13UhPR2EM5dQLs/k7mjif9+3KvB7i/wQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6db4e253-246d-4ed7-b833-e0d896805c07",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("f1cc0ba3-1050-43f7-86bd-98d4b7f7e216"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5e9c546c-5c8b-446b-834d-89d3fb270ac9",
                            Email = "jfonseca@pessoal.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "João Carlos Araújo Fonseca",
                            NormalizedEmail = "JFONSECA@PESSOAL.PT",
                            PasswordHash = "AQAAAAIAAYagAAAAENmFh/knB5U+tb/bOSLPIHkBqqkgHUv0msS8BrGdstihIWLsJom+6pAK5ijyjJ2yFA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4225b9c-3e5c-4526-a267-b55fc1dbdde8",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("804eef0f-2ec6-4b19-8b54-3373388f122b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57635711-b231-4e09-866c-cb8970cab382",
                            Email = "malves@pessoal.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Maria João Pereira Alves",
                            NormalizedEmail = "MALVES@PESSOAL.PT",
                            PasswordHash = "AQAAAAIAAYagAAAAEDOqoY/A9Id4uSg0FZ2Pn1IFcP59oG/uARhSavAgtFEgJ7ZcvoQkQVjjCvzc+BFQnQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "214c00b2-682f-4310-84ba-8cd7f466f20d",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("faf84edb-dd0b-4de9-90f9-3671335d01c7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4e88c59-a13a-44b2-bedf-11fcb65c5d2b",
                            Email = "sconceicao@pessoal.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Sandra Regina Queirós Azevedo Conceição",
                            NormalizedEmail = "SCONCEICAO@PESSOAL.PT",
                            PasswordHash = "AQAAAAIAAYagAAAAEBunlXGl4cP+eVgXp5N8WTrsPdSoFKudcKMZg47f2Ql3eJVJvOXqaYWopgeERwKVMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1d4e98cc-c78e-4abe-8164-aa41358c89b0",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("4b93b0ab-aed4-4eb1-a40b-900229359841"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c02f62ed-c493-4c6b-9925-7ed27623346f",
                            Email = "lneves@pessoal.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Luís Augusto Pinto Teixeira Neves",
                            NormalizedEmail = "LNEVES@PESSOAL.PT",
                            PasswordHash = "AQAAAAIAAYagAAAAEG9Qpe1DBFgyk9AfdJGGl6tzKtSDzBGv47Q6lSlf4vzR06PNT7XDSBirnaOeXgpq8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb09937d-40b0-4999-ae4b-8c551449e296",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("fb874eba-9c48-4340-a690-bebb2195d379"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be7e12e8-b4d4-4136-8be0-a022c5ae1b77",
                            Email = "admin@admin.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Admin",
                            NormalizedEmail = "ADMIN@ADMIN.PT",
                            PasswordHash = "AQAAAAIAAYagAAAAEKCqOA4Ilzwt3W3BSnRTmiTH4ahIz+YHJYBKCC8o/a/Mj4G0InEWw244yJamcd8tCA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f15dade-0a81-4238-ae5c-cad2ca8d0aae",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("backend.Entities.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("backend.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("backend.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("backend.Entities.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("backend.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
