// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260322142540_UpdateUsers")]
    partial class UpdateUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("fb874eba-9c48-4340-a690-bebb2195d379"),
                            RoleId = new Guid("418b0ac3-4dba-4ccf-883e-63fdd7ac62a9")
                        },
                        new
                        {
                            UserId = new Guid("e3a5e7de-975c-4d0f-ad17-cd563e62789a"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("251e0a52-d589-4845-ada8-daeb08be76ea"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("024e414c-d9d9-477a-bcb5-c6777bc7d3f9"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("0eae7ece-6671-4f83-9caa-fc2d8eadd9ae"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("db21f4f6-0eb4-4905-a604-ae5ab05696a6"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("f1cc0ba3-1050-43f7-86bd-98d4b7f7e216"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("804eef0f-2ec6-4b19-8b54-3373388f122b"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("faf84edb-dd0b-4de9-90f9-3671335d01c7"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        },
                        new
                        {
                            UserId = new Guid("4b93b0ab-aed4-4eb1-a40b-900229359841"),
                            RoleId = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("backend.Entities.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("418b0ac3-4dba-4ccf-883e-63fdd7ac62a9"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("52c71224-fe99-4ec0-9130-0f0de200eec9"),
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = new Guid("1704848a-5252-4f1f-82ef-9c4a751683d9"),
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        });
                });

            modelBuilder.Entity("backend.Entities.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3a5e7de-975c-4d0f-ad17-cd563e62789a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0981140-1b7c-4f33-a556-8ce519876d66",
                            Email = "alice.parker@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Alice Parker",
                            NormalizedEmail = "ALICE.PARKER@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGBfYpI3+jD07+rM2GxPKgXVtuWkZwoBn/tT/rO1Dv++Od4TmnaEU7A2RjoThhndhw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "82a360c3-37f9-42da-9dd2-e8af93b864fc",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("251e0a52-d589-4845-ada8-daeb08be76ea"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1635a002-94d3-44ef-86bb-57748d6b5654",
                            Email = "anna.collins@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Anna Collins",
                            NormalizedEmail = "ANNA.COLLINS@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAuHruPnRGlN3Xq20ky/PX5MNXAe5mrJJp8fioA34Sd4XtW85+jpgtAAKwzlTGKuGg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9dce8fcf-555e-475b-a676-0336b4a2886e",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("024e414c-d9d9-477a-bcb5-c6777bc7d3f9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5701278b-d7ec-40ba-9cd6-708c44563c16",
                            Email = "carol.green@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Carol Green",
                            NormalizedEmail = "CAROL.GREEN@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEurU6ZrLGLZfykokBpWyYEqEBP9Ga2xmzqYb8KMyWMRl2LHheX5tytt6vp3jQ33Iw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "75da7095-038e-4aca-970a-23122ef0e9c7",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("0eae7ece-6671-4f83-9caa-fc2d8eadd9ae"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e5607436-cab6-4d49-bf0a-2a3f595fd1f7",
                            Email = "philip.davis@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Philip Davis",
                            NormalizedEmail = "PHILIP.DAVIS@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMMzfiXlWCImAILZzfdcujU5I1uWAJgHgicvKd4G80A2Fg6r0ZOW8q1UH5NyOLO4Sw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bf601b92-1997-477c-a5b3-8958adc58474",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("db21f4f6-0eb4-4905-a604-ae5ab05696a6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "85ce73c8-afd1-4679-bd8b-8cf37c891da0",
                            Email = "florence.reed@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Florence Reed",
                            NormalizedEmail = "FLORENCE.REED@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDB4a6Yo341p9w4mikJR7pU0xXf13Z5gpdtuemxdA+NTetdyl9w6dRF37jE9VE2jyw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6db4e253-246d-4ed7-b833-e0d896805c07",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("f1cc0ba3-1050-43f7-86bd-98d4b7f7e216"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5e9c546c-5c8b-446b-834d-89d3fb270ac9",
                            Email = "john.foster@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "John Foster",
                            NormalizedEmail = "JOHN.FOSTER@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF2EjLloRAqhHZ8b1HEsgK2YIyl7XbbbqB2HV0MqHaUt7Om6Phww7bHt5wWfTbUzcQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4225b9c-3e5c-4526-a267-b55fc1dbdde8",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("804eef0f-2ec6-4b19-8b54-3373388f122b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57635711-b231-4e09-866c-cb8970cab382",
                            Email = "mary.allen@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Mary Allen",
                            NormalizedEmail = "MARY.ALLEN@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENUU2a07QfAav4csT7QQxJEG5qHO7BC1ocT8VCnrU0SmstwHmvDSHs1IVOl0FUMeSA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "214c00b2-682f-4310-84ba-8cd7f466f20d",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("faf84edb-dd0b-4de9-90f9-3671335d01c7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4e88c59-a13a-44b2-bedf-11fcb65c5d2b",
                            Email = "sandra.quinn@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Sandra Quinn",
                            NormalizedEmail = "SANDRA.QUINN@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPZvG5cBjgzAhS8jvYxpr8rtLbRZuu8FgUQuW1Pl4EVejZEv6vORf8WPAT92dhy1jw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1d4e98cc-c78e-4abe-8164-aa41358c89b0",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("4b93b0ab-aed4-4eb1-a40b-900229359841"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c02f62ed-c493-4c6b-9925-7ed27623346f",
                            Email = "louis.newton@company.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Louis Newton",
                            NormalizedEmail = "LOUIS.NEWTON@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBmxJR6DJhSAJXMBEfA/TJZP1YHN+nr06fXrihnFYVoJrHYcniXntWWcaPfXt/LT5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb09937d-40b0-4999-ae4b-8c551449e296",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("fb874eba-9c48-4340-a690-bebb2195d379"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be7e12e8-b4d4-4136-8be0-a022c5ae1b77",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Admin",
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEP/raVK8/qrnvjvsRu6cGjGOPZv1611RXWzhFYqkx9Si244Mh7KN5ggGMfltIkxSaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f15dade-0a81-4238-ae5c-cad2ca8d0aae",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("backend.Entities.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("backend.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("backend.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("backend.Entities.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("backend.Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
